import "./globals.css";
import Navbar from "@components/Navbar";
import AuthProvider from "@components/AuthProvider";

export const metadata = {
  title: "Market Place App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-red-600 via-red-400 to-red-200">
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
